---
Name: FlexSlider
---
SlideImage:
  db:
    Name: Varchar(255)
    Title: Varchar(255)
    Description: Text
    SortOrder: Int
    ShowSlide: Boolean
  has_one:
    Image: Image
    Page: Page
    PageLink: SiteTree
  singular_name:
    - Slide
  plural_name:
    - Slides
  default_order:
    - SortOrder
  summary_fields:
    Image.CMSThumbnail: Image
    Name: Name
  searchable_fields:
    Name: Name
    Title: Title
    Description: Description